version: "3.9"
services:
  api:
    build:
      context: ./DesafioFullStackPlenoBack
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./DesafioFullStackPlenoFront
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
